import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { fromImageToUrl, API_URL } from "../../utils/urls";
import { toTwoDP } from "../../utils/format";
import { Grid } from "@mui/material";
import { Paper } from "@mui/material";

export default function Home({ products }) {
    // console.log(`${API_URL}/api/products?populate=*`);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Products</h1>
            {products.data?.map((product) => {
                return (
                    <Link href={`/products/${product.id}`} key={product.id}>
                        <a>
                            <div>
                                <Image
                                    src={fromImageToUrl(
                                        product.attributes.image
                                    )}
                                    alt="image"
                                    width="100%"
                                    height="100%"
                                    // layout="responsive"
                                    objectFit="contain"
                                />
                            </div>
                            <div>
                                {product.attributes.name}{" "}
                                {toTwoDP(product.attributes.price)}
                            </div>
                        </a>
                    </Link>
                );
            })}
        </div>
    );
}

export async function getStaticProps() {
    // fetch the data
    const product_res = await fetch(`${API_URL}/api/products/?populate=*`);
    const products = await product_res.json();
    // return the data as props
    return {
        props: { products },
    };
}
