import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { fromImageToUrl, API_URL } from "../../utils/urls";
import { toTwoDP } from "../../utils/format";
import { Grid } from "@mui/material";
import { Paper } from "@mui/material";
import Button from "@mui/material/Button";
import * as React from "react";
import { Container } from "@mui/material";
import ProductCard from "../../components/ProductCard";

export default function ProductsPage({ products }) {
    // console.log(`${API_URL}/api/products?populate=*`);
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>Products</h1>
            <Container>
                <Grid container spacing={5}>
                    {products.data?.map((product) => {
                        return (
                            <Grid item key={product.id} xs={12} sm={6} md={4}>
                                <ProductCard product={product} />
                            </Grid>
                        );
                    })}
                </Grid>
            </Container>
        </div>
    );
}

export async function getStaticProps() {
    // fetch the data
    const product_res = await fetch(`${API_URL}/api/products/?populate=*`);
    const products = await product_res.json();
    // return the data as props
    return {
        props: { products },
    };
}
