import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import { fromImageToUrl, API_URL } from "../../utils/urls";
import { toTwoDP } from "../../utils/format";
import { Grid } from "@mui/material";

export default function Home({ artworks }) {
    // console.log(`${API_URL}/api/artworks?populate=*`);
    return (
        <div className={styles.container}>
            <Head>
                <title>artworks</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <h1>artworks</h1>
            {artworks.data?.map((art) => {
                return (
                    <Link href={`/artworks/${art.id}`} key={art.id}>
                        <a>
                            <div>
                                <Image
                                    src={fromImageToUrl(art.attributes.image)}
                                    alt="image"
                                    width="100%"
                                    height="100%"
                                    // layout="responsive"
                                    objectFit="contain"
                                />
                            </div>
                            <div>
                                {art.attributes.name}{" "}
                                {toTwoDP(art.attributes.price)}
                            </div>
                        </a>
                    </Link>
                );
            })}
        </div>
    );
}

export async function getStaticProps() {
    // fetch the data
    const art_res = await fetch(`${API_URL}/api/artworks/?populate=*`);
    const artworks = await art_res.json();
    // return the data as props
    return {
        props: { artworks },
    };
}
